version: "3.9"
services:
  redis:
    image: redis
    container_name: httpRateLimiter-redis
    volumes:
      - ./cache-data:/data
    ports:
      - "6379:6379"
  redis-commander:
    container_name: httpRateLimiter-redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081"
